spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-34-197-84-74.compute-1.amazonaws.com:5432/dbgob8bc5vraqo
    username: swyxhvzinfimjs
    password: 89de4f0ea0a77b55932fb3f6ce416a29d11ace49821f1dcf32ca4fcb157df9c5

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
app:
  generation:
    create: false
